### ISSUE TITLE
"Wikipedia coordinates" link in readme is not working

### ISSUE THREAD

**Issue by matkoniecz** [simone-f/wikipedia-tags-in-osm#18]

**Comment by simone-f** [comment]
Thank you.

The link does not work, but it is also old.
I'll fix it.

FYI, the new link is here:
https://tools.wmflabs.org/wp-world/dumps/new_red0wd4.gz

I found it here:
https://de.wikipedia.org/wiki/Wikipedia:WikiProjekt_Georeferenzierung/Hauptseite/Wikipedia-World
